project_id = "pliris-ba-bot"

[api]
enabled = true
port = 54321

[db]
port = 54322

[storage]
enabled = true
file_size_limit = "32MiB"

[storage.buckets.knowledge-base]
public = false
file_size_limit = "32MiB"
allowed_mime_types = ["application/pdf"]

[auth]
enabled = true